name: Check

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  secrets:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Run Trufflehog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: false

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: binary
          version: latest

  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate an SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: sbom.json
          artifact-name: sbom
      - name: Check for CVEs
        uses: anchore/scan-action@v7
        with:
          sbom: sbom.json
          severity-cutoff: high

  sast:
    name: Static App Security Test
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Perform a SAST scan
        run: semgrep scan --config auto .
